import { Container } from '@chakra-ui/react';
import { useWalletModal } from '@solana/wallet-adapter-react-ui';
import { DynamicPricingCandyMachine } from '@strata-foundation/marketplace-ui';
import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import { BrowserView, MobileView } from "react-device-detect";
import { Toaster } from 'react-hot-toast';

const Home: NextPage = () => {
  const { setVisible } = useWalletModal();
  return (
    <div style={{ color: "white", backgroundColor: "black", height: "100vh" }}>
      <Head>
        <title>Create Next App </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container pt={12}>
          <DynamicPricingCandyMachine
            onConnectWallet={() => setVisible(true)}
            candyMachineId={process.env.NEXT_PUBLIC_CANDYMACHINE_ID}
          />
        </Container>
        <BrowserView>
          <Toaster
            position="bottom-left"
            containerStyle={{
              width: "420px",
            }}
          />
        </BrowserView>
        <MobileView>
          <Toaster
            position="bottom-center"
            containerStyle={{
              margin: "0 auto",
              width: "90%",
              maxWidth: "420px",
            }}
          />
        </MobileView>
      </main>
    </div>
  );
};

export default Home;
